query GetAllBrands @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it only lists general product information.") {
  brands {
    id
    name
    website
    description
  }
}

query GetDiscGolfBagDetails($id: UUID!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it only fetches details of a specific disc golf bag.") {
  discGolfBag(id: $id) {
    id
    name
    brand {
      name
    }
    minDiscCapacity
    maxDiscCapacity
    description
    imageUrl
    price
    features
  }
}

mutation CreateRecommendation($discGolfBagId: UUID!, $notes: String) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it allows them to create recommendations tied to their user ID.") {
  recommendation_insert(data: {
    userId_expr: "auth.uid",
    discGolfBagId: $discGolfBagId,
    notes: $notes
  })
}

query GetUserRecommendations @auth(level: USER) {
  recommendations(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    notes
    discGolfBag {
      name
      brand {
        name
      }
    }
    createdAt
  }
}